### PR TITLE
PDR-452: lazy loading causing issues with site datepicker

### LINKED ISSUE #452: DR - Date picker: months getting stacked when arrow keys are clicked
**Describe the bug**
When making an edit (minor, legal name, or repeal), when the date picker is opened, clicking the arrow (< or >) keys causes months to become stacked on top of each other.

**To Reproduce**
1. Go to any site
2. Click on Edit and select Minor edit, Legal name, or Repeal
3. Open the date picker
4. Click the forward or back arrow keys and notice the month panels stack up

**Expected behavior**
Month should go forward or backward with only one calendar panel visible.

https://github.com/bcgov/parks-data-register/assets/65189530/1ce2cb70-81eb-44c8-9bf0-83db53bf8568

### PR DESCRIPTION
**Pull request by cameronpettit**
Fixes #452.

Not a datepicker issue so much as a lazy loading issue. The datepicker rendering changes but the old rendering is not removed. Patched in a similar way to protected areas - `detectChanges` wrapped in a 0s timeout.

### CODE REVIEW

File: pdr-admin/src/app/protected-area/site/site-manage/site-edit-form/site-edit-form.component.ts [hunk 1]
```diff
@@ -186,6 +187,12 @@ export class SiteEditFormComponent implements OnInit, OnDestroy {
 
   // empty function to allow use of shared template
   onDatePickerInteract() {
+    // TODO: Fix this bug
+    // For some reason, if we do detectChanages outisde of a setTimeout
+    // Month picker and year picker breaks
+    setTimeout(() => {
+      this.cdr.detectChanges();
```
Comment (danieltruong) [inline pdr-admin/src/app/protected-area/site/site-manage/site-edit-form/site-edit-form.component.ts:194]: "this.cdr.detectChanges() only runs change detection for the current component (and descendants). If setFirstItemActive() causes changes elsewhere this is not covered. setTimeout() or zone.run(...) or ApplicationRef.tick() causes change detection to be run for the whole application and therefore every binding is covered, not only the current component."

image

Comment (cameronpettit) [reply pdr-admin/src/app/protected-area/site/site-manage/site-edit-form/site-edit-form.component.ts:194]: image

I tried the `ApplicationRef` methods and `setTimeout()` without `detectChanges` cuz I thought it felt cleaner but it didn't actually fix anything. Pretty sure when you and I ran into this problem with the datepicker for protected areas we ran into the same thing.

Its like Angular wants us to subscribe to `onChanges` and just run `detectChanges` every time something happens if we are running with lazy loading. He hmmmmmmmmmmmmmmmmmm

**Review by marklise — APPROVED** [review]
